name: Test, Build and Deploy Docs

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '!master'
      - 'dev**'

jobs:
  build-and-deploy:
    name: Deploy Docs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Master
        uses: actions/checkout@master

      - name: Test
        run: |
          npm install
          # npm run build --if-present
          npm test
          npm run changelog

      # - name: Build and Deploy Docs
      #   uses: JamesIves/github-pages-deploy-action@master
      #   env:
      #     ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      #     BRANCH: gh-pages
      #     FOLDER: docs/.vuepress/dist
      #     BUILD_SCRIPT: npm install && npm run docs:build
