name: Test, Build and Deploy Docs

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "!master"
      - "dev**"

jobs:
  build-and-deploy:
    name: Test and Deploy Docs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Master
        uses: actions/checkout@master

      - name: Test
        run: |
          npm ci
          # npm run build --if-present
          # npm run deploy
          npm run test
          npm run docs:build
          # npm run changelog

      # - name: Coveralls Parallel
      #   uses: coverallsapp/github-action@master
      #   with:
      #     github-token: ${{ secrets.ACCESS_TOKEN }}
      #     parallel: true
      #     path-to-lcov: ./coverage/lcov.info

      # - name: Coveralls Finished
      #   uses: coverallsapp/github-action@master
      #   with:
      #     github-token: ${{ secrets.ACCESS_TOKEN }}
      #     parallel-finished: true

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          access_token: ${{ secrets.ACCESS_TOKEN }}
          branch: gh-pages
          folder: docs/.vuepress/dist
          build_script: npm run deploy
