name: Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '!master'
      - 'dev**'

jobs:
  build:

    runs-on: ubuntu-latest

    # strategy:
    #   matrix:
    #     node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
      run: |
        npm i
        npm run docs:build
        npm run changelog
    # - name: Use Node.js ${{ matrix.node-version }}
    #   uses: actions/setup-node@v1
    #   with:
    #     node-version: ${{ matrix.node-version }}

    - name: Build and Deploy Docs
      uses: JamesIves/github-pages-deploy-action@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        EXTERNAL_REPOSITORY: rain120/rain120.github.io/awesome-javascript-code-implementation
        PUBLISH_BRANCH: master
        PUBLISH_DIR: docs/.vuepress/dist
        CI: true

    - name: Test
      run: |
        # npm run build --if-present
        npm test
        # npm run coveralls
        # npm run build
        npm run changelog
      env:
        CI: true
